version: '3.1'
services: 
  web:
    build: .
    ports: 
      - "80:8080"
    environment: 
      PORT: 8080
      DB_USERNAME: sync
      DB_PASSWORD: linusE123
      DB_DATABASE: sync
    restart: always
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"
    restart: always
    command: [--auth]